# create a makefile variable named CC for your C/C++ compiler (es gcc, c++, ... )

#Link libraries if necessary

#create the target 'bin/prefixsum_bandwidth_test' which needs 'prefixsum_bandwidth_test.c' and 'my_time_lib.o', generate the folder 'bin' and compile get_time_test.c using CC and OPT

#create the target 'clean' which recursively remove the folders 'bin' and 'obj'

